none:
  name: 'No Boots'
  default: true
  icon:
    type: 'BARRIER'

soldier:
  name: 'Soldier Boots'
  cost: 650
  icon:
    type: 'LEATHER_BOOTS'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'

elite:
  name: 'Elite Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'BLUE'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'BLUE'

majestic:
  name: 'Majestic Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'YELLOW'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'YELLOW'

commander:
  name: 'Commander Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'BLACK'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'BLACK'

marine:
  name: 'Marine Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'GREEN'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'GREEN'

swat:
  name: 'SWAT Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'GRAY'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'GRAY'

spec-ops:
  name: 'Spec Ops Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'RED'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'RED'

invader:
  name: 'Invader Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'ORANGE'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'ORANGE'

revenge:
  name: 'Revenge Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'PURPLE'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'PURPLE'

space:
  name: 'Space Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'AQUA'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'AQUA'

slime:
  name: 'Slime Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'LIME'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'LIME'

snow:
  name: 'Snow Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'WHITE'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'WHITE'

fashionista:
  name: 'Fashionista Boots'
  cost: 2250
  icon:
    type: 'LEATHER_BOOTS'
    color: 'FUCHSIA'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'FUCHSIA'

medieval:
  name: 'Medieval Boots'
  cost: 2750
  icon:
    type: 'CHAINMAIL_BOOTS'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'CHAINMAIL_BOOTS'

budder:
  name: 'Budder Boots'
  cost: 3375
  icon:
    type: 'GOLD_BOOTS'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'GOLD_BOOTS'

sweg:
  name: 'Sweg Boots'
  cost: 4500
  icon:
    type: 'DIAMOND_BOOTS'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'DIAMOND_BOOTS'

disco:
  name: 'Disco Boots'
  cost: 75000
  icon:
    type: 'LEATHER_BOOTS'
    color: 'MAROON'
    lore:
    - '&7Cosmetic armor'
    flags:
    - hide attributes
  item:
    type: 'LEATHER_BOOTS'
    color: 'MAROON'
