# The color could be written in many ways, there's the "normal" way (color names) and the advanced way:
# The advanced way is as follows:
# color: R;G;B (ex. color: 255;255;255 == WHITE)
# color: #hex (ex. color: #ffffff == WHITE)
yellow:
  name: 'Yellow Laser'
  cost: 0
  default: true
  icon:
    type: 'INK_SACK'
    data: 11
    lore:
    - '&7Choose a firework color!'
  firework-color: 'YELLOW'

green:
  name: 'Green Laser'
  cost: 4000
  icon:
    type: 'INK_SACK'
    data: 2
    lore:
    - '&7Choose a firework color!'
  firework-color: 'GREEN'

white:
  name: 'White Laser'
  cost: 4000
  icon:
    type: 'INK_SACK'
    data: 15
    lore:
    - '&7Choose a firework color!'
  firework-color: 'WHITE'

red:
  name: 'Red Laser'
  cost: 5000
  icon:
    type: 'INK_SACK'
    data: 1
    lore:
    - '&7Choose a firework color!'
  firework-color: 'RED'

blue:
  name: 'Blue Laser'
  cost: 7000
  icon:
    type: 'INK_SACK'
    data: 4
    lore:
    - '&7Choose a firework color!'
  firework-color: 'BLUE'

purple:
  name: 'Purple Laser'
  cost: 8000
  icon:
    type: 'INK_SACK'
    data: 5
    lore:
    - '&7Choose a firework color!'
  firework-color: 'PURPLE'

pink:
  name: 'Pink Laser'
  cost: 8000
  icon:
    type: 'INK_SACK'
    data: 9
    lore:
    - '&7Choose a firework color!'
  firework-color: 'FUCHSIA'

gold:
  name: 'Gold Laser'
  cost: 50000
  icon:
    type: 'GOLD_INGOT'
    lore:
    - '&7Choose a firework color!'
  firework-color: 'OLIVE'

emerald:
  name: 'Emerald Laser'
  cost: 50000
  icon:
    type: 'EMERALD'
    lore:
    - '&7Choose a firework color!'
  firework-color: 'LIME'

diamond:
  name: 'Diamond Laser'
  cost: 50000
  icon:
    type: 'DIAMOND'
    lore:
    - '&7Choose a firework color!'
  firework-color: 'AQUA'

gray:
  name: 'Gray Laser'
  cost: 50000
  icon:
    type: 'INK_SACK'
    data: 8
    lore:
    - '&7Choose a firework color!'
  firework-color: 'GRAY'

orange:
  name: 'Orange Laser'
  cost: 100000
  icon:
    type: 'INK_SACK'
    data: 14
    lore:
    - '&7Choose a firework color!'
  firework-color: 'ORANGE'

silver:
  name: 'Silver Laser'
  cost: 250000
  icon:
    type: 'INK_SACK'
    data: 7
    lore:
    - '&7Choose a firework color!'
  firework-color: 'SILVER'

black:
  name: 'Black Laser'
  cost: 500000
  icon:
    type: 'INK_SACK'
    lore:
    - '&7Choose a firework color!'
  firework-color: 'BLACK'
